# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Build & Release

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: |
        cd badminton
        GOOS=linux GOARCH=amd64 go build -o badminton.linux
        GOOS=darwin GOARCH=amd64 go build -o badminton.mac

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: "Development Build"
        tag_name: "v0.1.${{ github.run_number }}"
        files: |
          badminton/badminton.linux
          badminton/badminton.mac
